import { formatDate } from "../utils/utils";

export const formatedData = (data)=> {
    let formattedData = data.map(entry => {
        let newEntry = {...entry};
        if(newEntry.startDate) {
            let startDate = formatDate(newEntry.startDate);
            newEntry.startDate = startDate
        }
        if(newEntry.dateOfBirth) {
            let dateOfBirth = formatDate(newEntry.dateOfBirth);
            newEntry.dateOfBirth = dateOfBirth;
        }
        
        return newEntry;
    });

    return formattedData;
};




export const data = [
    {
        firstName: "Libbi",
        lastName: "Buist",
        startDate: "10/29/2023",
        department: "Legal",
        dateOfBirth: "11/19/2023",
        street: "8129",
        city: "Bumpe",
        state: null,
        zipCode: null
    },
    {
        firstName: "Greggory",
        lastName: "Beteriss",
        startDate: "5/3/2023",
        department: "Services",
        dateOfBirth: "11/28/2023",
        street: "358",
        city: "Lauro de Freitas",
        state: null,
        zipCode: "42700-000"
    },
    {
        firstName: "Ivar",
        lastName: "Gever",
        startDate: "8/17/2023",
        department: "Support",
        dateOfBirth: "12/6/2023",
        street: "538",
        city: "Pontevedra",
        state: "Galicia",
        zipCode: "36005"
    },
    {
        firstName: "Alexandrina",
        lastName: "Le Strange",
        startDate: "6/25/2023",
        department: "Legal",
        dateOfBirth: "5/27/2023",
        street: "8",
        city: "Kopayhorod",
        state: null,
        zipCode: null
    },
    {
        firstName: "Robert",
        lastName: "Turn",
        startDate: "5/7/2023",
        department: "Product Management",
        dateOfBirth: "12/13/2022",
        street: "05",
        city: "Nizhniy Bestyakh",
        state: null,
        zipCode: "678080"
    },
    {
        firstName: "Reinhard",
        lastName: "Dodson",
        startDate: "5/1/2023",
        department: "Research and Development",
        dateOfBirth: "6/1/2023",
        street: "9",
        city: "Laidian",
        state: null,
        zipCode: null
    },
    {
        firstName: "Omero",
        lastName: "Arnett",
        startDate: "6/3/2023",
        department: "Human Resources",
        dateOfBirth: "11/30/2023",
        street: "7",
        city: "Kolç",
        state: null,
        zipCode: null
    },
    {
        firstName: "Krista",
        lastName: "Burdess",
        startDate: "8/16/2023",
        department: "Accounting",
        dateOfBirth: "10/8/2023",
        street: "7162",
        city: "Magisterial",
        state: "Zacatecas",
        zipCode: "99750"
    },
    {
        firstName: "Giraldo",
        lastName: "Elfitt",
        startDate: "7/13/2023",
        department: "Product Management",
        dateOfBirth: "11/6/2023",
        street: "1",
        city: "Cipanjang",
        state: null,
        zipCode: null
    },
    {
        firstName: "Afton",
        lastName: "Vigurs",
        startDate: "1/21/2023",
        department: "Business Development",
        dateOfBirth: "11/16/2023",
        street: "065",
        city: "Pakisaji",
        state: null,
        zipCode: null
    },
    {
        firstName: "Teressa",
        lastName: "Postans",
        startDate: "6/18/2023",
        department: "Training",
        dateOfBirth: "5/29/2023",
        street: "3024",
        city: "Svecha",
        state: null,
        zipCode: "612040"
    },
    {
        firstName: "Towney",
        lastName: "Bransdon",
        startDate: "10/23/2023",
        department: "Engineering",
        dateOfBirth: "8/27/2023",
        street: "42071",
        city: "Aībak",
        state: null,
        zipCode: null
    },
    {
        firstName: "Rhetta",
        lastName: "Crowcum",
        startDate: "10/29/2023",
        department: "Support",
        dateOfBirth: "1/17/2023",
        street: "30",
        city: "Cabucgayan",
        state: null,
        zipCode: "6550"
    },
    {
        firstName: "Wilbert",
        lastName: "Pasfield",
        startDate: "3/4/2023",
        department: "Research and Development",
        dateOfBirth: "4/19/2023",
        street: "2",
        city: "Kowo",
        state: null,
        zipCode: null
    },
    {
        firstName: "Zach",
        lastName: "O'Flaverty",
        startDate: "12/30/2022",
        department: "Accounting",
        dateOfBirth: "2/12/2023",
        street: "08486",
        city: "Laotai",
        state: null,
        zipCode: null
    },
    {
        firstName: "Britta",
        lastName: "Ruberry",
        startDate: "3/12/2023",
        department: "Business Development",
        dateOfBirth: "5/27/2023",
        street: "9334",
        city: "Kayima",
        state: null,
        zipCode: null
    },
    {
        firstName: "Irv",
        lastName: "Newbury",
        startDate: "10/23/2023",
        department: "Sales",
        dateOfBirth: "10/26/2023",
        street: "5",
        city: "‘Afak",
        state: null,
        zipCode: null
    },
    {
        firstName: "Ernest",
        lastName: "Bayles",
        startDate: "9/29/2023",
        department: "Business Development",
        dateOfBirth: "4/15/2023",
        street: "2027",
        city: "Kanganpur",
        state: null,
        zipCode: "55000"
    },
    {
        firstName: "Dimitri",
        lastName: "Sebire",
        startDate: "11/16/2023",
        department: "Business Development",
        dateOfBirth: "6/28/2023",
        street: "5018",
        city: "Suizhou",
        state: null,
        zipCode: null
    },
    {
        firstName: "Gordan",
        lastName: "Huertas",
        startDate: "12/4/2023",
        department: "Marketing",
        dateOfBirth: "9/30/2023",
        street: "5036",
        city: "Muang Xay",
        state: null,
        zipCode: null
    },
    {
        firstName: "Ronni",
        lastName: "Shankster",
        startDate: "11/16/2023",
        department: "Product Management",
        dateOfBirth: "5/23/2023",
        street: "63",
        city: "Los Algarrobos",
        state: null,
        zipCode: null
    },
    {
        firstName: "Algernon",
        lastName: "Lothean",
        startDate: "11/18/2023",
        department: "Business Development",
        dateOfBirth: "10/4/2023",
        street: "7",
        city: "Velký Týnec",
        state: null,
        zipCode: "783 72"
    },
    {
        firstName: "Fonzie",
        lastName: "Kibbye",
        startDate: "1/24/2023",
        department: "Sales",
        dateOfBirth: "11/18/2023",
        street: "7627",
        city: "Plagiári",
        state: null,
        zipCode: null
    },
    {
        firstName: "Courtnay",
        lastName: "Disney",
        startDate: "8/21/2023",
        department: "Business Development",
        dateOfBirth: "11/1/2023",
        street: "78079",
        city: "Dibulla",
        state: null,
        zipCode: "446017"
    },
    {
        firstName: "Annetta",
        lastName: "Kynsey",
        startDate: "7/19/2023",
        department: "Human Resources",
        dateOfBirth: "7/27/2023",
        street: "7",
        city: "Maroanging",
        state: null,
        zipCode: null
    },
    {
        firstName: "Dania",
        lastName: "Fishpoole",
        startDate: "11/3/2023",
        department: "Training",
        dateOfBirth: "6/19/2023",
        street: "3593",
        city: "Cikiruh Wetan",
        state: null,
        zipCode: null
    },
    {
        firstName: "Leonid",
        lastName: "Sambrook",
        startDate: "5/7/2023",
        department: "Marketing",
        dateOfBirth: "2/26/2023",
        street: "85",
        city: "Cajicá",
        state: null,
        zipCode: "250247"
    },
    {
        firstName: "Trefor",
        lastName: "Lyfield",
        startDate: "8/23/2023",
        department: "Research and Development",
        dateOfBirth: "5/16/2023",
        street: "440",
        city: "Shiqiao",
        state: null,
        zipCode: null
    },
    {
        firstName: "Lynette",
        lastName: "Kerbey",
        startDate: "10/23/2023",
        department: "Services",
        dateOfBirth: "5/10/2023",
        street: "693",
        city: "Rzhev",
        state: null,
        zipCode: "172389"
    },
    {
        firstName: "Em",
        lastName: "Seabrooke",
        startDate: "11/27/2023",
        department: "Engineering",
        dateOfBirth: "4/16/2023",
        street: "5135",
        city: "Santiago dos Velhos",
        state: "Lisboa",
        zipCode: "2630-505"
    },
    {
        firstName: "Sibylle",
        lastName: "Russon",
        startDate: "9/16/2023",
        department: "Training",
        dateOfBirth: "10/5/2023",
        street: "4",
        city: "Zhitan",
        state: null,
        zipCode: null
    },
    {
        firstName: "Perla",
        lastName: "Bontoft",
        startDate: "3/28/2023",
        department: "Business Development",
        dateOfBirth: "4/27/2023",
        street: "279",
        city: "Ghāro",
        state: null,
        zipCode: "73210"
    },
    {
        firstName: "Devora",
        lastName: "Enevoldsen",
        startDate: "8/19/2023",
        department: "Business Development",
        dateOfBirth: "7/5/2023",
        street: "8288",
        city: "Krutja e Poshtme",
        state: null,
        zipCode: null
    },
    {
        firstName: "Sarena",
        lastName: "Adrienne",
        startDate: "9/1/2023",
        department: "Business Development",
        dateOfBirth: "4/13/2023",
        street: "79",
        city: "Tracal",
        state: null,
        zipCode: null
    },
    {
        firstName: "Mabelle",
        lastName: "Huston",
        startDate: "10/18/2023",
        department: "Services",
        dateOfBirth: "4/17/2023",
        street: "21",
        city: "Zoumi",
        state: null,
        zipCode: null
    },
    {
        firstName: "Wilden",
        lastName: "Beharrell",
        startDate: "11/2/2023",
        department: "Human Resources",
        dateOfBirth: "5/23/2023",
        street: "91433",
        city: "Montbéliard",
        state: "Franche-Comté",
        zipCode: "25215 CEDEX"
    },
    {
        firstName: "Uri",
        lastName: "Hurich",
        startDate: "3/4/2023",
        department: "Sales",
        dateOfBirth: "8/4/2023",
        street: "27",
        city: "Vladimir",
        state: null,
        zipCode: "356555"
    },
    {
        firstName: "Derick",
        lastName: "Aslin",
        startDate: "6/21/2023",
        department: "Support",
        dateOfBirth: "2/10/2023",
        street: "51",
        city: "Fukushima-shi",
        state: null,
        zipCode: "969-1661"
    },
    {
        firstName: "Cointon",
        lastName: "Biskupski",
        startDate: "5/6/2023",
        department: "Business Development",
        dateOfBirth: "10/6/2023",
        street: "5",
        city: "Barqueiro",
        state: "Leiria",
        zipCode: "2430-604"
    },
    {
        firstName: "Bradan",
        lastName: "Romayn",
        startDate: "6/14/2023",
        department: "Research and Development",
        dateOfBirth: "5/12/2023",
        street: "15935",
        city: "Horní Lideč",
        state: null,
        zipCode: "756 12"
    },
    {
        firstName: "Holden",
        lastName: "Lansdowne",
        startDate: "9/18/2023",
        department: "Support",
        dateOfBirth: "3/28/2023",
        street: "812",
        city: "Schiedam postbusnummers",
        state: "Provincie Zuid-Holland",
        zipCode: "3109"
    },
    {
        firstName: "Jess",
        lastName: "Indge",
        startDate: "9/26/2023",
        department: "Human Resources",
        dateOfBirth: "4/14/2023",
        street: "58",
        city: "Borzęcin",
        state: null,
        zipCode: "32-825"
    },
    {
        firstName: "Kirsti",
        lastName: "Cattini",
        startDate: "4/24/2023",
        department: "Business Development",
        dateOfBirth: "4/20/2023",
        street: "52",
        city: "Xin’an",
        state: null,
        zipCode: null
    },
    {
        firstName: "Natassia",
        lastName: "Raff",
        startDate: "6/8/2023",
        department: "Research and Development",
        dateOfBirth: "3/6/2023",
        street: "2",
        city: "Bantarsari Kulon",
        state: null,
        zipCode: null
    },
    {
        firstName: "Cary",
        lastName: "Dupoy",
        startDate: "12/3/2023",
        department: "Marketing",
        dateOfBirth: "4/3/2023",
        street: "2",
        city: "Kula",
        state: null,
        zipCode: null
    },
    {
        firstName: "Godfrey",
        lastName: "Pearsey",
        startDate: "11/12/2023",
        department: "Services",
        dateOfBirth: "6/21/2023",
        street: "10",
        city: "Mae Lan",
        state: null,
        zipCode: "94180"
    },
    {
        firstName: "Wally",
        lastName: "Trytsman",
        startDate: "11/29/2023",
        department: "Business Development",
        dateOfBirth: "12/2/2023",
        street: "564",
        city: "Nkpor",
        state: null,
        zipCode: null
    },
    {
        firstName: "Penn",
        lastName: "Ferrari",
        startDate: "11/27/2023",
        department: "Training",
        dateOfBirth: "3/11/2023",
        street: "21",
        city: "Chinandega",
        state: null,
        zipCode: null
    },
    {
        firstName: "Elisha",
        lastName: "Jermin",
        startDate: "4/14/2023",
        department: "Training",
        dateOfBirth: "9/3/2023",
        street: "5",
        city: "Ukhta",
        state: null,
        zipCode: "169309"
    },
    {
        firstName: "Fabien",
        lastName: "Amar",
        startDate: "8/21/2023",
        department: "Marketing",
        dateOfBirth: "2/21/2023",
        street: "81",
        city: "Pasirhuni",
        state: null,
        zipCode: null
    },
    {
        firstName: "Tate",
        lastName: "Taggett",
        startDate: "10/23/2023",
        department: "Sales",
        dateOfBirth: "8/10/2023",
        street: "695",
        city: "Ninh Giang",
        state: null,
        zipCode: null
    },
    {
        firstName: "Ike",
        lastName: "Pedgrift",
        startDate: "2/6/2023",
        department: "Research and Development",
        dateOfBirth: "11/27/2023",
        street: "2",
        city: "Mutum Biyu",
        state: null,
        zipCode: null
    },
    {
        firstName: "Courtenay",
        lastName: "Mandifield",
        startDate: "10/30/2023",
        department: "Sales",
        dateOfBirth: "3/11/2023",
        street: "74590",
        city: "Mingyu",
        state: null,
        zipCode: null
    },
    {
        firstName: "Antonin",
        lastName: "Martinat",
        startDate: "5/23/2023",
        department: "Training",
        dateOfBirth: "5/10/2023",
        street: "4971",
        city: "Panolan",
        state: null,
        zipCode: null
    },
    {
        firstName: "Dorine",
        lastName: "Toffts",
        startDate: "4/11/2023",
        department: "Business Development",
        dateOfBirth: "11/20/2023",
        street: "4",
        city: "Gilowice",
        state: null,
        zipCode: "34-322"
    },
    {
        firstName: "Simona",
        lastName: "Danslow",
        startDate: "3/29/2023",
        department: "Marketing",
        dateOfBirth: "3/3/2023",
        street: "6",
        city: "Samālūţ",
        state: null,
        zipCode: null
    },
    {
        firstName: "Vasilis",
        lastName: "Bridgestock",
        startDate: "6/10/2023",
        department: "Marketing",
        dateOfBirth: "7/1/2023",
        street: "00",
        city: "Palmar de Varela",
        state: null,
        zipCode: "083087"
    },
    {
        firstName: "Pall",
        lastName: "Hammerberg",
        startDate: "5/6/2023",
        department: "Accounting",
        dateOfBirth: "10/13/2023",
        street: "6733",
        city: "Hinigaran",
        state: null,
        zipCode: "4026"
    },
    {
        firstName: "Portia",
        lastName: "Tallent",
        startDate: "3/15/2023",
        department: "Engineering",
        dateOfBirth: "11/28/2023",
        street: "58039",
        city: "San Miguel",
        state: null,
        zipCode: "8301"
    },
    {
        firstName: "Linnea",
        lastName: "Winley",
        startDate: "2/26/2023",
        department: "Legal",
        dateOfBirth: "7/3/2023",
        street: "02332",
        city: "Santa Bárbara de Padrões",
        state: "Beja",
        zipCode: "7780-460"
    },
    {
        firstName: "Hanna",
        lastName: "Czyz",
        startDate: "4/18/2023",
        department: "Engineering",
        dateOfBirth: "5/26/2023",
        street: "445",
        city: "Niutang",
        state: null,
        zipCode: null
    },
    {
        firstName: "Janet",
        lastName: "Pullen",
        startDate: "1/13/2023",
        department: "Sales",
        dateOfBirth: "3/29/2023",
        street: "3",
        city: "Jacksonville",
        state: "Florida",
        zipCode: "32209"
    },
    {
        firstName: "Hernando",
        lastName: "Crilly",
        startDate: "7/4/2023",
        department: "Sales",
        dateOfBirth: "5/29/2023",
        street: "55043",
        city: "Vol’no-Nadezhdinskoye",
        state: null,
        zipCode: "238603"
    },
    {
        firstName: "Jenny",
        lastName: "Penritt",
        startDate: "7/12/2023",
        department: "Research and Development",
        dateOfBirth: "9/18/2023",
        street: "1",
        city: "Petřvald",
        state: null,
        zipCode: "735 41"
    },
    {
        firstName: "Eustacia",
        lastName: "Fugere",
        startDate: "10/12/2023",
        department: "Marketing",
        dateOfBirth: "4/18/2023",
        street: "9378",
        city: "Paraíso das Águas",
        state: null,
        zipCode: "36420-000"
    },
    {
        firstName: "Glennis",
        lastName: "Craw",
        startDate: "3/8/2023",
        department: "Business Development",
        dateOfBirth: "2/1/2023",
        street: "223",
        city: "Grabovci",
        state: null,
        zipCode: "22215"
    },
    {
        firstName: "Allan",
        lastName: "Morrad",
        startDate: "9/15/2023",
        department: "Research and Development",
        dateOfBirth: "7/12/2023",
        street: "95117",
        city: "Lawdar",
        state: null,
        zipCode: null
    },
    {
        firstName: "Derick",
        lastName: "Bernot",
        startDate: "1/18/2023",
        department: "Accounting",
        dateOfBirth: "9/18/2023",
        street: "07803",
        city: "Beibei",
        state: null,
        zipCode: null
    },
    {
        firstName: "Tiffi",
        lastName: "Stoddard",
        startDate: "11/8/2023",
        department: "Research and Development",
        dateOfBirth: "4/12/2023",
        street: "25241",
        city: "Papeete",
        state: null,
        zipCode: null
    },
    {
        firstName: "Guilbert",
        lastName: "Redmore",
        startDate: "6/25/2023",
        department: "Training",
        dateOfBirth: "12/18/2022",
        street: "56",
        city: "Yaozhou",
        state: null,
        zipCode: null
    },
    {
        firstName: "Lavina",
        lastName: "Richardin",
        startDate: "12/13/2022",
        department: "Accounting",
        dateOfBirth: "10/24/2023",
        street: "10",
        city: "Ōiso",
        state: null,
        zipCode: "259-1220"
    },
    {
        firstName: "Pinchas",
        lastName: "Barday",
        startDate: "2/9/2023",
        department: "Research and Development",
        dateOfBirth: "7/26/2023",
        street: "8911",
        city: "Mouzáki",
        state: null,
        zipCode: null
    },
    {
        firstName: "Greg",
        lastName: "Peyzer",
        startDate: "10/28/2023",
        department: "Support",
        dateOfBirth: "1/6/2023",
        street: "8753",
        city: "Shijia",
        state: null,
        zipCode: null
    },
    {
        firstName: "Rusty",
        lastName: "Motte",
        startDate: "8/19/2023",
        department: "Product Management",
        dateOfBirth: "10/28/2023",
        street: "90",
        city: "Brejos",
        state: "Setúbal",
        zipCode: "2860-318"
    },
    {
        firstName: "Annissa",
        lastName: "Dunlop",
        startDate: "11/21/2023",
        department: "Training",
        dateOfBirth: "3/4/2023",
        street: "969",
        city: "Khanino",
        state: null,
        zipCode: "301420"
    },
    {
        firstName: "Nichol",
        lastName: "Plowright",
        startDate: "12/21/2022",
        department: "Training",
        dateOfBirth: "5/29/2023",
        street: "25963",
        city: "Sulak",
        state: null,
        zipCode: "427030"
    },
    {
        firstName: "Bryon",
        lastName: "Ingrem",
        startDate: "10/2/2023",
        department: "Services",
        dateOfBirth: "4/25/2023",
        street: "9714",
        city: "Kuala Lumpur",
        state: "Kuala Lumpur",
        zipCode: "50490"
    },
    {
        firstName: "Jared",
        lastName: "Burnes",
        startDate: "9/5/2023",
        department: "Engineering",
        dateOfBirth: "1/1/2023",
        street: "51203",
        city: "Rio Branco do Sul",
        state: null,
        zipCode: "83540-000"
    },
    {
        firstName: "Josefa",
        lastName: "Tieraney",
        startDate: "7/26/2023",
        department: "Business Development",
        dateOfBirth: "8/15/2023",
        street: "31740",
        city: "Gandu",
        state: null,
        zipCode: null
    },
    {
        firstName: "Jeff",
        lastName: "Gabey",
        startDate: "11/15/2023",
        department: "Support",
        dateOfBirth: "10/5/2023",
        street: "700",
        city: "Pingya",
        state: null,
        zipCode: null
    },
    {
        firstName: "Anatol",
        lastName: "Flode",
        startDate: "8/18/2023",
        department: "Human Resources",
        dateOfBirth: "8/30/2023",
        street: "183",
        city: "Gongji",
        state: null,
        zipCode: null
    },
    {
        firstName: "Cazzie",
        lastName: "Vakhrushev",
        startDate: "4/25/2023",
        department: "Sales",
        dateOfBirth: "2/26/2023",
        street: "163",
        city: "Pital",
        state: null,
        zipCode: "414068"
    },
    {
        firstName: "Ferdie",
        lastName: "Mirando",
        startDate: "6/28/2023",
        department: "Marketing",
        dateOfBirth: "10/11/2023",
        street: "0",
        city: "Kiupo",
        state: null,
        zipCode: "1173"
    },
    {
        firstName: "Debora",
        lastName: "Panks",
        startDate: "9/30/2023",
        department: "Training",
        dateOfBirth: "2/2/2023",
        street: "83",
        city: "Xincun",
        state: null,
        zipCode: null
    },
    {
        firstName: "Mikey",
        lastName: "Graham",
        startDate: "6/23/2023",
        department: "Sales",
        dateOfBirth: "6/18/2023",
        street: "75",
        city: "Hatogaya-honchō",
        state: null,
        zipCode: "336-0036"
    },
    {
        firstName: "Lilllie",
        lastName: "Tryme",
        startDate: "12/4/2023",
        department: "Business Development",
        dateOfBirth: "4/21/2023",
        street: "1",
        city: "Melres",
        state: "Porto",
        zipCode: "4515-465"
    },
    {
        firstName: "Cyrillus",
        lastName: "Seiffert",
        startDate: "7/14/2023",
        department: "Support",
        dateOfBirth: "10/2/2023",
        street: "2979",
        city: "Pongkor",
        state: null,
        zipCode: null
    },
    {
        firstName: "Martie",
        lastName: "Scally",
        startDate: "7/5/2023",
        department: "Support",
        dateOfBirth: "9/8/2023",
        street: "412",
        city: "Öndörhoshuu",
        state: null,
        zipCode: null
    },
    {
        firstName: "Lukas",
        lastName: "Cockin",
        startDate: "1/28/2023",
        department: "Accounting",
        dateOfBirth: "5/16/2023",
        street: "2932",
        city: "Brudzeń Duży",
        state: null,
        zipCode: "09-414"
    },
    {
        firstName: "Francoise",
        lastName: "Arnould",
        startDate: "11/27/2023",
        department: "Research and Development",
        dateOfBirth: "5/20/2023",
        street: "63",
        city: "Bairro dos Marinheiros",
        state: "Setúbal",
        zipCode: "2950-691"
    },
    {
        firstName: "Teodor",
        lastName: "Molineaux",
        startDate: "10/14/2023",
        department: "Research and Development",
        dateOfBirth: "2/13/2023",
        street: "6779",
        city: "Baishi",
        state: null,
        zipCode: null
    },
    {
        firstName: "Arleyne",
        lastName: "Churchlow",
        startDate: "11/4/2023",
        department: "Services",
        dateOfBirth: "7/9/2023",
        street: "64585",
        city: "São Lourenço do Sul",
        state: null,
        zipCode: "96170-000"
    },
    {
        firstName: "Eamon",
        lastName: "Tebald",
        startDate: "7/17/2023",
        department: "Human Resources",
        dateOfBirth: "10/2/2023",
        street: "80",
        city: "Colonia Elisa",
        state: null,
        zipCode: "3515"
    },
    {
        firstName: "Sarine",
        lastName: "Burch",
        startDate: "5/21/2023",
        department: "Marketing",
        dateOfBirth: "4/27/2023",
        street: "45",
        city: "Juranalas",
        state: null,
        zipCode: null
    },
    {
        firstName: "Franny",
        lastName: "Pither",
        startDate: "10/25/2023",
        department: "Marketing",
        dateOfBirth: "5/16/2023",
        street: "23986",
        city: "Cotmon",
        state: null,
        zipCode: "4500"
    },
    {
        firstName: "El",
        lastName: "Torbeck",
        startDate: "2/9/2023",
        department: "Sales",
        dateOfBirth: "11/8/2023",
        street: "63",
        city: "Sobral",
        state: "Viana do Castelo",
        zipCode: "4990-585"
    },
    {
        firstName: "Claudine",
        lastName: "Ruzek",
        startDate: "5/20/2023",
        department: "Marketing",
        dateOfBirth: "1/29/2023",
        street: "861",
        city: "Virolahti",
        state: null,
        zipCode: "49901"
    },
    {
        firstName: "Matias",
        lastName: "Kemell",
        startDate: "9/10/2023",
        department: "Product Management",
        dateOfBirth: "9/16/2023",
        street: "957",
        city: "Askersund",
        state: "Örebro",
        zipCode: "696 30"
    },
    {
        firstName: "Hayden",
        lastName: "Faye",
        startDate: "9/29/2023",
        department: "Marketing",
        dateOfBirth: "10/3/2023",
        street: "0739",
        city: "Wushi",
        state: null,
        zipCode: null
    },
    {
        firstName: "Illa",
        lastName: "Gammidge",
        startDate: "5/16/2023",
        department: "Business Development",
        dateOfBirth: "9/30/2023",
        street: "052",
        city: "Tambaú",
        state: null,
        zipCode: "13710-000"
    },
    {
        firstName: "Jamil",
        lastName: "Heselwood",
        startDate: "6/2/2023",
        department: "Business Development",
        dateOfBirth: "9/20/2023",
        street: "004",
        city: "Mitry-Mory",
        state: "Île-de-France",
        zipCode: "77294 CEDEX"
    },
    {
        firstName: "Rickie",
        lastName: "Vergine",
        startDate: "11/1/2023",
        department: "Research and Development",
        dateOfBirth: "8/22/2023",
        street: "0061",
        city: "Jedlnia-Letnisko",
        state: null,
        zipCode: "26-630"
    },
    {
        firstName: "Maud",
        lastName: "Jordanson",
        startDate: "12/4/2023",
        department: "Legal",
        dateOfBirth: "1/21/2023",
        street: "4",
        city: "Al Finţās",
        state: null,
        zipCode: null
    },
    {
        firstName: "Gabriella",
        lastName: "Craghead",
        startDate: "5/26/2023",
        department: "Services",
        dateOfBirth: "11/4/2023",
        street: "65",
        city: "Jiulong",
        state: null,
        zipCode: null
    },
    {
        firstName: "Miguelita",
        lastName: "Fallawe",
        startDate: "6/14/2023",
        department: "Business Development",
        dateOfBirth: "8/10/2023",
        street: "7",
        city: "Cochabamba",
        state: null,
        zipCode: null
    },
    {
        firstName: "Rorie",
        lastName: "Rabbitts",
        startDate: "5/14/2023",
        department: "Services",
        dateOfBirth: "7/23/2023",
        street: "277",
        city: "Mirovka",
        state: null,
        zipCode: null
    },
    {
        firstName: "Maureene",
        lastName: "Waylen",
        startDate: "8/30/2023",
        department: "Engineering",
        dateOfBirth: "1/6/2023",
        street: "984",
        city: "La Celia",
        state: null,
        zipCode: "662037"
    },
    {
        firstName: "Priscella",
        lastName: "Dunbobbin",
        startDate: "1/5/2023",
        department: "Engineering",
        dateOfBirth: "10/15/2023",
        street: "37",
        city: "Majur",
        state: null,
        zipCode: null
    },
    {
        firstName: "Birgit",
        lastName: "Brownell",
        startDate: "9/26/2023",
        department: "Marketing",
        dateOfBirth: "9/4/2023",
        street: "063",
        city: "Wonocolo",
        state: null,
        zipCode: null
    },
    {
        firstName: "Nari",
        lastName: "Jupp",
        startDate: "12/13/2022",
        department: "Marketing",
        dateOfBirth: "12/26/2022",
        street: "2157",
        city: "Rutana",
        state: null,
        zipCode: null
    },
    {
        firstName: "Glori",
        lastName: "Giacopini",
        startDate: "11/21/2023",
        department: "Business Development",
        dateOfBirth: "2/26/2023",
        street: "5928",
        city: "Psará",
        state: null,
        zipCode: null
    },
    {
        firstName: "Staci",
        lastName: "Bellocht",
        startDate: "11/10/2023",
        department: "Product Management",
        dateOfBirth: "6/8/2023",
        street: "2162",
        city: "Baru Timur",
        state: null,
        zipCode: null
    },
    {
        firstName: "Jennette",
        lastName: "Vassall",
        startDate: "11/25/2023",
        department: "Engineering",
        dateOfBirth: "4/15/2023",
        street: "4423",
        city: "Tuusniemi",
        state: null,
        zipCode: "71201"
    },
    {
        firstName: "Lacee",
        lastName: "Fearnyough",
        startDate: "12/15/2022",
        department: "Engineering",
        dateOfBirth: "7/9/2023",
        street: "96106",
        city: "Maipú",
        state: null,
        zipCode: "5517"
    },
    {
        firstName: "Dwain",
        lastName: "Wesgate",
        startDate: "4/20/2023",
        department: "Training",
        dateOfBirth: "1/11/2023",
        street: "4000",
        city: "Hazlov",
        state: null,
        zipCode: "350 02"
    },
    {
        firstName: "Alla",
        lastName: "Frewer",
        startDate: "10/2/2023",
        department: "Support",
        dateOfBirth: "10/19/2023",
        street: "17776",
        city: "Balky",
        state: null,
        zipCode: null
    },
    {
        firstName: "Misti",
        lastName: "Hollyar",
        startDate: "10/20/2023",
        department: "Human Resources",
        dateOfBirth: "11/21/2023",
        street: "9477",
        city: "Xiaojin",
        state: null,
        zipCode: null
    },
    {
        firstName: "Pauly",
        lastName: "Buckel",
        startDate: "8/31/2023",
        department: "Engineering",
        dateOfBirth: "12/1/2023",
        street: "5",
        city: "Guadalupe",
        state: "Puebla",
        zipCode: "72124"
    },
    {
        firstName: "Alvan",
        lastName: "Berthomier",
        startDate: "5/9/2023",
        department: "Research and Development",
        dateOfBirth: "1/25/2023",
        street: "7249",
        city: "Chowṉêy",
        state: null,
        zipCode: null
    },
    {
        firstName: "Davis",
        lastName: "Van de Castele",
        startDate: "4/28/2023",
        department: "Business Development",
        dateOfBirth: "5/5/2023",
        street: "5042",
        city: "Zhongshangang",
        state: null,
        zipCode: null
    },
    {
        firstName: "Ashton",
        lastName: "Crosen",
        startDate: "7/10/2023",
        department: "Human Resources",
        dateOfBirth: "1/4/2023",
        street: "637",
        city: "Ocala",
        state: "Florida",
        zipCode: "34479"
    },
    {
        firstName: "Windy",
        lastName: "Brittan",
        startDate: "8/4/2023",
        department: "Human Resources",
        dateOfBirth: "12/22/2022",
        street: "4",
        city: "Minas de Matahambre",
        state: null,
        zipCode: null
    },
    {
        firstName: "Cody",
        lastName: "Cattermole",
        startDate: "1/31/2023",
        department: "Product Management",
        dateOfBirth: "1/17/2023",
        street: "09",
        city: "Promyshlennaya",
        state: null,
        zipCode: "652380"
    },
    {
        firstName: "Molli",
        lastName: "Evemy",
        startDate: "2/13/2023",
        department: "Services",
        dateOfBirth: "9/15/2023",
        street: "7975",
        city: "Zhongbu",
        state: null,
        zipCode: null
    },
    {
        firstName: "Alfred",
        lastName: "Seabrooke",
        startDate: "12/5/2023",
        department: "Marketing",
        dateOfBirth: "6/1/2023",
        street: "33166",
        city: "Tours",
        state: "Centre",
        zipCode: "37922 CEDEX 9"
    },
    {
        firstName: "Marlon",
        lastName: "Buie",
        startDate: "4/3/2023",
        department: "Services",
        dateOfBirth: "4/3/2023",
        street: "669",
        city: "Kremidivka",
        state: null,
        zipCode: null
    },
    {
        firstName: "Cliff",
        lastName: "Shakle",
        startDate: "12/10/2022",
        department: "Training",
        dateOfBirth: "6/26/2023",
        street: "0",
        city: "Krasnokamsk",
        state: null,
        zipCode: "397325"
    },
    {
        firstName: "Bailey",
        lastName: "Burvill",
        startDate: "4/28/2023",
        department: "Services",
        dateOfBirth: "4/7/2023",
        street: "9528",
        city: "Surgut",
        state: null,
        zipCode: "628408"
    },
    {
        firstName: "Conroy",
        lastName: "Ferie",
        startDate: "12/20/2022",
        department: "Training",
        dateOfBirth: "8/6/2023",
        street: "24",
        city: "Rouyuan",
        state: null,
        zipCode: null
    },
    {
        firstName: "Farr",
        lastName: "Swaffield",
        startDate: "8/10/2023",
        department: "Support",
        dateOfBirth: "4/12/2023",
        street: "8556",
        city: "Pajé",
        state: null,
        zipCode: null
    },
    {
        firstName: "Allyn",
        lastName: "Luke",
        startDate: "9/22/2023",
        department: "Marketing",
        dateOfBirth: "4/20/2023",
        street: "832",
        city: "Springfield",
        state: "Missouri",
        zipCode: "65810"
    },
    {
        firstName: "Nollie",
        lastName: "Mitchel",
        startDate: "5/13/2023",
        department: "Support",
        dateOfBirth: "6/6/2023",
        street: "3",
        city: "Bang Yai",
        state: null,
        zipCode: "11140"
    },
    {
        firstName: "Hamlin",
        lastName: "O'Mullally",
        startDate: "7/3/2023",
        department: "Support",
        dateOfBirth: "5/25/2023",
        street: "0",
        city: "Aulnay-sous-Bois",
        state: "Île-de-France",
        zipCode: "93604 CEDEX"
    },
    {
        firstName: "Rowen",
        lastName: "Kopps",
        startDate: "6/2/2023",
        department: "Sales",
        dateOfBirth: "12/19/2022",
        street: "1",
        city: "High Prairie",
        state: "Alberta",
        zipCode: "L8N"
    },
    {
        firstName: "Anna-maria",
        lastName: "Brownsell",
        startDate: "1/24/2023",
        department: "Support",
        dateOfBirth: "11/3/2023",
        street: "0425",
        city: "Takāb",
        state: null,
        zipCode: null
    },
    {
        firstName: "Peyton",
        lastName: "Dealtry",
        startDate: "3/27/2023",
        department: "Marketing",
        dateOfBirth: "1/9/2023",
        street: "366",
        city: "Tangkilsari",
        state: null,
        zipCode: null
    },
    {
        firstName: "Roderic",
        lastName: "Wolpert",
        startDate: "2/6/2023",
        department: "Human Resources",
        dateOfBirth: "8/2/2023",
        street: "131",
        city: "Huangtudian",
        state: null,
        zipCode: null
    },
    {
        firstName: "Verene",
        lastName: "Tremberth",
        startDate: "9/25/2023",
        department: "Business Development",
        dateOfBirth: "5/16/2023",
        street: "13",
        city: "Xiadu",
        state: null,
        zipCode: null
    },
    {
        firstName: "Adrianna",
        lastName: "Feron",
        startDate: "5/6/2023",
        department: "Research and Development",
        dateOfBirth: "10/24/2023",
        street: "389",
        city: "Tianxingchang",
        state: null,
        zipCode: null
    },
    {
        firstName: "Haley",
        lastName: "Doby",
        startDate: "7/26/2023",
        department: "Accounting",
        dateOfBirth: "7/14/2023",
        street: "3063",
        city: "Ranao",
        state: null,
        zipCode: "3526"
    },
    {
        firstName: "Matias",
        lastName: "de Guise",
        startDate: "5/2/2023",
        department: "Accounting",
        dateOfBirth: "4/3/2023",
        street: "564",
        city: "Mileb",
        state: null,
        zipCode: "6088"
    },
    {
        firstName: "Faythe",
        lastName: "Ashment",
        startDate: "10/16/2023",
        department: "Legal",
        dateOfBirth: "6/17/2023",
        street: "696",
        city: "Kulautuva",
        state: null,
        zipCode: "53093"
    },
    {
        firstName: "Florida",
        lastName: "Brimmell",
        startDate: "1/18/2023",
        department: "Marketing",
        dateOfBirth: "9/5/2023",
        street: "7",
        city: "Luoqiao",
        state: null,
        zipCode: null
    },
    {
        firstName: "Michel",
        lastName: "Canete",
        startDate: "3/22/2023",
        department: "Business Development",
        dateOfBirth: "3/5/2023",
        street: "4",
        city: "Aqtoghay",
        state: null,
        zipCode: null
    },
    {
        firstName: "Kinnie",
        lastName: "Raithby",
        startDate: "6/17/2023",
        department: "Services",
        dateOfBirth: "10/8/2023",
        street: "3",
        city: "Sapataria",
        state: "Lisboa",
        zipCode: "2590-431"
    },
    {
        firstName: "Zora",
        lastName: "Lotze",
        startDate: "7/13/2023",
        department: "Training",
        dateOfBirth: "7/27/2023",
        street: "2013",
        city: "Cova Figueira",
        state: null,
        zipCode: null
    },
    {
        firstName: "Dale",
        lastName: "Blandford",
        startDate: "6/21/2023",
        department: "Product Management",
        dateOfBirth: "1/22/2023",
        street: "39",
        city: "Florencia",
        state: null,
        zipCode: "195047"
    },
    {
        firstName: "Blythe",
        lastName: "Bohden",
        startDate: "12/7/2022",
        department: "Business Development",
        dateOfBirth: "1/9/2023",
        street: "013",
        city: "Kopparberg",
        state: "Örebro",
        zipCode: "714 31"
    },
    {
        firstName: "Ulysses",
        lastName: "Summers",
        startDate: "2/12/2023",
        department: "Human Resources",
        dateOfBirth: "2/19/2023",
        street: "66",
        city: "Bodø",
        state: "Nordland",
        zipCode: "8010"
    },
    {
        firstName: "Dayle",
        lastName: "Biskupiak",
        startDate: "7/10/2023",
        department: "Marketing",
        dateOfBirth: "12/21/2022",
        street: "930",
        city: "Koloniya Zastav’ye",
        state: null,
        zipCode: null
    },
    {
        firstName: "Anson",
        lastName: "Ladbrooke",
        startDate: "6/14/2023",
        department: "Product Management",
        dateOfBirth: "4/20/2023",
        street: "44",
        city: "Qingkou",
        state: null,
        zipCode: null
    },
    {
        firstName: "Orran",
        lastName: "McGray",
        startDate: "4/25/2023",
        department: "Accounting",
        dateOfBirth: "1/2/2023",
        street: "0",
        city: "Tintina",
        state: null,
        zipCode: "3743"
    },
    {
        firstName: "Harriot",
        lastName: "Goncalo",
        startDate: "10/27/2023",
        department: "Services",
        dateOfBirth: "3/1/2023",
        street: "28626",
        city: "Mérignac",
        state: "Aquitaine",
        zipCode: "33709 CEDEX"
    },
    {
        firstName: "Sandor",
        lastName: "Charnock",
        startDate: "9/24/2023",
        department: "Sales",
        dateOfBirth: "12/17/2022",
        street: "41",
        city: "Fenshui",
        state: null,
        zipCode: null
    },
    {
        firstName: "Elladine",
        lastName: "Folkerd",
        startDate: "9/25/2023",
        department: "Services",
        dateOfBirth: "10/13/2023",
        street: "26",
        city: "Salakuray",
        state: null,
        zipCode: null
    },
    {
        firstName: "Rabbi",
        lastName: "Fish",
        startDate: "3/11/2023",
        department: "Services",
        dateOfBirth: "5/27/2023",
        street: "66105",
        city: "Shicong",
        state: null,
        zipCode: null
    },
    {
        firstName: "Agnesse",
        lastName: "Broxap",
        startDate: "2/11/2023",
        department: "Human Resources",
        dateOfBirth: "12/4/2023",
        street: "7174",
        city: "Guder",
        state: null,
        zipCode: null
    },
    {
        firstName: "Tirrell",
        lastName: "Filson",
        startDate: "3/25/2023",
        department: "Support",
        dateOfBirth: "12/31/2022",
        street: "28",
        city: "Xihuaiba",
        state: null,
        zipCode: null
    },
    {
        firstName: "Kyle",
        lastName: "Tournay",
        startDate: "6/1/2023",
        department: "Sales",
        dateOfBirth: "10/24/2023",
        street: "492",
        city: "Zelenchukskaya",
        state: null,
        zipCode: "369227"
    },
    {
        firstName: "Olivie",
        lastName: "Haddy",
        startDate: "4/16/2023",
        department: "Research and Development",
        dateOfBirth: "1/8/2023",
        street: "12",
        city: "BelizeCity",
        state: null,
        zipCode: null
    },
    {
        firstName: "Laurens",
        lastName: "Mabbett",
        startDate: "7/28/2023",
        department: "Engineering",
        dateOfBirth: "3/24/2023",
        street: "177",
        city: "Ziniaré",
        state: null,
        zipCode: null
    },
    {
        firstName: "Tobe",
        lastName: "MacGhee",
        startDate: "12/18/2022",
        department: "Support",
        dateOfBirth: "2/10/2023",
        street: "8",
        city: "Bojawa",
        state: null,
        zipCode: null
    },
    {
        firstName: "Saundra",
        lastName: "Byars",
        startDate: "10/27/2023",
        department: "Services",
        dateOfBirth: "5/12/2023",
        street: "7703",
        city: "Kampungbaru",
        state: null,
        zipCode: null
    },
    {
        firstName: "Elisabeth",
        lastName: "Piele",
        startDate: "10/5/2023",
        department: "Training",
        dateOfBirth: "3/27/2023",
        street: "80",
        city: "Krajan Keboromo",
        state: null,
        zipCode: null
    },
    {
        firstName: "Pippy",
        lastName: "Cruces",
        startDate: "11/27/2023",
        department: "Sales",
        dateOfBirth: "3/29/2023",
        street: "144",
        city: "Jiaoshi",
        state: null,
        zipCode: null
    },
    {
        firstName: "Juliet",
        lastName: "Jeanequin",
        startDate: "12/23/2022",
        department: "Services",
        dateOfBirth: "2/20/2023",
        street: "34",
        city: "Xitan",
        state: null,
        zipCode: null
    },
    {
        firstName: "Kimble",
        lastName: "Carrodus",
        startDate: "11/24/2023",
        department: "Support",
        dateOfBirth: "6/29/2023",
        street: "7595",
        city: "Sydney",
        state: "New South Wales",
        zipCode: "1134"
    },
    {
        firstName: "Tremain",
        lastName: "Wince",
        startDate: "6/27/2023",
        department: "Human Resources",
        dateOfBirth: "12/5/2023",
        street: "2",
        city: "Ugra",
        state: null,
        zipCode: "215435"
    },
    {
        firstName: "Sylvia",
        lastName: "Conville",
        startDate: "12/14/2022",
        department: "Engineering",
        dateOfBirth: "11/27/2023",
        street: "82640",
        city: "Logovskoye",
        state: null,
        zipCode: "671633"
    },
    {
        firstName: "Hynda",
        lastName: "Smallshaw",
        startDate: "4/27/2023",
        department: "Engineering",
        dateOfBirth: "8/6/2023",
        street: "388",
        city: "Freixo de Numão",
        state: "Guarda",
        zipCode: "5155-205"
    },
    {
        firstName: "Lester",
        lastName: "Carmody",
        startDate: "4/22/2023",
        department: "Support",
        dateOfBirth: "11/26/2023",
        street: "26567",
        city: "Washington",
        state: "District of Columbia",
        zipCode: "20078"
    },
    {
        firstName: "Gunner",
        lastName: "Coram",
        startDate: "3/15/2023",
        department: "Training",
        dateOfBirth: "2/5/2023",
        street: "50",
        city: "Ikhtiman",
        state: null,
        zipCode: "2049"
    },
    {
        firstName: "Janos",
        lastName: "Claige",
        startDate: "10/11/2023",
        department: "Human Resources",
        dateOfBirth: "3/12/2023",
        street: "2174",
        city: "Falun",
        state: "Dalarna",
        zipCode: "791 91"
    },
    {
        firstName: "Selena",
        lastName: "Lindenfeld",
        startDate: "10/31/2023",
        department: "Marketing",
        dateOfBirth: "10/30/2023",
        street: "898",
        city: "Shuanglongchang",
        state: null,
        zipCode: null
    },
    {
        firstName: "Nedda",
        lastName: "Genner",
        startDate: "8/16/2023",
        department: "Training",
        dateOfBirth: "2/22/2023",
        street: "0",
        city: "Sarnia",
        state: "Ontario",
        zipCode: "N7V"
    },
    {
        firstName: "Valeda",
        lastName: "Saph",
        startDate: "8/10/2023",
        department: "Product Management",
        dateOfBirth: "10/13/2023",
        street: "252",
        city: "Longxing",
        state: null,
        zipCode: null
    },
    {
        firstName: "Harry",
        lastName: "Herity",
        startDate: "1/31/2023",
        department: "Product Management",
        dateOfBirth: "3/19/2023",
        street: "65",
        city: "Shuitian",
        state: null,
        zipCode: null
    },
    {
        firstName: "Analiese",
        lastName: "Lavalle",
        startDate: "1/17/2023",
        department: "Product Management",
        dateOfBirth: "6/23/2023",
        street: "43",
        city: "Itaperuçu",
        state: null,
        zipCode: "83560-000"
    },
    {
        firstName: "Sanford",
        lastName: "Lammie",
        startDate: "2/10/2023",
        department: "Sales",
        dateOfBirth: "5/29/2023",
        street: "947",
        city: "Ketapang",
        state: null,
        zipCode: null
    },
    {
        firstName: "Esme",
        lastName: "Lehemann",
        startDate: "6/10/2023",
        department: "Engineering",
        dateOfBirth: "3/4/2023",
        street: "02",
        city: "Tubualá",
        state: null,
        zipCode: null
    },
    {
        firstName: "Adolphe",
        lastName: "Plester",
        startDate: "11/20/2023",
        department: "Sales",
        dateOfBirth: "3/22/2023",
        street: "1",
        city: "Tianjiazhai",
        state: null,
        zipCode: null
    },
    {
        firstName: "Idaline",
        lastName: "Purnell",
        startDate: "7/4/2023",
        department: "Marketing",
        dateOfBirth: "12/10/2022",
        street: "5971",
        city: "Psyzh",
        state: null,
        zipCode: "369110"
    },
    {
        firstName: "Allianora",
        lastName: "Niche",
        startDate: "1/24/2023",
        department: "Product Management",
        dateOfBirth: "4/28/2023",
        street: "548",
        city: "Kilju",
        state: null,
        zipCode: null
    },
    {
        firstName: "Carolin",
        lastName: "Capron",
        startDate: "9/22/2023",
        department: "Engineering",
        dateOfBirth: "10/14/2023",
        street: "52561",
        city: "Rayevskiy",
        state: null,
        zipCode: "452122"
    },
    {
        firstName: "Barbra",
        lastName: "Ackroyd",
        startDate: "9/8/2023",
        department: "Business Development",
        dateOfBirth: "3/11/2023",
        street: "32",
        city: "Tembongraja",
        state: null,
        zipCode: null
    },
    {
        firstName: "Hollis",
        lastName: "Palombi",
        startDate: "9/1/2023",
        department: "Support",
        dateOfBirth: "10/18/2023",
        street: "75836",
        city: "Białośliwie",
        state: null,
        zipCode: "89-340"
    },
    {
        firstName: "Kimberly",
        lastName: "Leeburn",
        startDate: "11/22/2023",
        department: "Legal",
        dateOfBirth: "9/17/2023",
        street: "1172",
        city: "Sanshengyuan",
        state: null,
        zipCode: null
    },
    {
        firstName: "Lucian",
        lastName: "Jarman",
        startDate: "7/6/2023",
        department: "Legal",
        dateOfBirth: "9/13/2023",
        street: "50564",
        city: "Zagazig",
        state: null,
        zipCode: null
    },
    {
        firstName: "Katalin",
        lastName: "Duggan",
        startDate: "12/26/2022",
        department: "Services",
        dateOfBirth: "9/27/2023",
        street: "1",
        city: "Maltahöhe",
        state: null,
        zipCode: null
    },
    {
        firstName: "Roxana",
        lastName: "Showt",
        startDate: "9/9/2023",
        department: "Marketing",
        dateOfBirth: "8/31/2023",
        street: "5855",
        city: "Littleton",
        state: "Colorado",
        zipCode: "80126"
    },
    {
        firstName: "Sigismond",
        lastName: "McRinn",
        startDate: "3/27/2023",
        department: "Engineering",
        dateOfBirth: "2/23/2023",
        street: "61",
        city: "Tireman Timur",
        state: null,
        zipCode: null
    },
    {
        firstName: "Shem",
        lastName: "Skedge",
        startDate: "7/4/2023",
        department: "Accounting",
        dateOfBirth: "6/6/2023",
        street: "1204",
        city: "Cheb",
        state: null,
        zipCode: "350 02"
    },
    {
        firstName: "Nessie",
        lastName: "Muddicliffe",
        startDate: "8/6/2023",
        department: "Services",
        dateOfBirth: "12/9/2022",
        street: "0079",
        city: "Berlin",
        state: "Berlin",
        zipCode: "10179"
    },
    {
        firstName: "Griz",
        lastName: "Mortimer",
        startDate: "2/22/2023",
        department: "Research and Development",
        dateOfBirth: "12/24/2022",
        street: "954",
        city: "Puan",
        state: null,
        zipCode: null
    },
    {
        firstName: "Andriana",
        lastName: "Matzke",
        startDate: "8/2/2023",
        department: "Marketing",
        dateOfBirth: "11/24/2023",
        street: "86",
        city: "Djambala",
        state: null,
        zipCode: null
    },
    {
        firstName: "Jessie",
        lastName: "Bauduccio",
        startDate: "2/9/2023",
        department: "Accounting",
        dateOfBirth: "6/6/2023",
        street: "05",
        city: "Bidyā",
        state: null,
        zipCode: null
    },
    {
        firstName: "Dulcy",
        lastName: "Basey",
        startDate: "8/16/2023",
        department: "Product Management",
        dateOfBirth: "5/15/2023",
        street: "51994",
        city: "Tournon-sur-Rhône",
        state: "Rhône-Alpes",
        zipCode: "07304 CEDEX"
    },
    {
        firstName: "Magnum",
        lastName: "Lodemann",
        startDate: "8/5/2023",
        department: "Engineering",
        dateOfBirth: "1/29/2023",
        street: "743",
        city: "Paris 13",
        state: "Île-de-France",
        zipCode: "75643 CEDEX 13"
    },
    {
        firstName: "Natale",
        lastName: "Outlaw",
        startDate: "4/5/2023",
        department: "Accounting",
        dateOfBirth: "8/6/2023",
        street: "547",
        city: "Liusi",
        state: null,
        zipCode: null
    },
    {
        firstName: "Michaeline",
        lastName: "Yegorov",
        startDate: "11/1/2023",
        department: "Product Management",
        dateOfBirth: "11/6/2023",
        street: "4900",
        city: "Kalchevaya",
        state: null,
        zipCode: null
    }
];